"""Print a golden quant Markdown section from a synthetic fixture.

    python -m explain_my_option.pricing.demo_report vol_crush
"""

from __future__ import annotations

import sys

from explain_my_option.data.synthetic import load_fixture
from explain_my_option.pricing.config import EngineConfig
from explain_my_option.pricing.facade import price_and_attribute
from explain_my_option.report_generator import build_quant_section


def render_fixture(name: str, *, config: EngineConfig | None = None) -> str:
    snap, surf = load_fixture(name)
    result = price_and_attribute(snap, surf, config=config or EngineConfig.from_env())
    body = build_quant_section(snap, result)
    header = "<!-- generated by src.pricing.demo_report; do not edit -->\n\n"
    return header + body + "\n"


def main(argv: list[str] | None = None) -> int:
    args = argv if argv is not None else sys.argv[1:]
    name = args[0] if args else "vol_crush"
    sys.stdout.write(render_fixture(name))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
